function k(a,b,c){this.l=typeof b=="function"?b:function(){};this.d=typeof c=="function"?c:function(){};this.input=a;this.h=false}
k.prototype={g:function(){var a=9,b,c;this.b=[];for(this.a=[];a--;){this.a[a]=[];this.b[a]=[];for(b=9;b--;){this.a[a][b]=[];this.b[a][b]=null;for(c=9;c--;)this.a[a][b][c]=true}}for(a=9;a--;)for(b=9;b--;){c=parseInt(this.input[a][b],10);isNaN(c)||this.c(a,b,c-1,false)}this.h=true;if(this.f()){this.d(false);return false}},i:function(){this.h||this.g();this.e();if(this.j()){this.d(true);return true}if(this.f()){this.d(false);return false}this.k();if(this.j()){this.d(true);return true}this.d(false);return false},
e:function(){for(var a=9,b,c,e,d,g=3,f,h,i,j;a--;)for(c=9;c--;){b=f=i=0;e=h=j=[];for(d=9;d--;){if(this.b[a][c]===null&&this.a[a][c][d]===true){++b;e=[a,c,d]}if(this.b[a][d]===null&&this.a[a][d][c]===true){++f;h=[a,d,c]}if(this.b[d][a]===null&&this.a[d][a][c]===true){++i;j=[d,a,c]}}b==1&&this.c(e[0],e[1],e[2]);f==1&&this.c(h[0],h[1],h[2]);i==1&&this.c(j[0],j[1],j[2]);if(b==1||f==1||i==1){this.e();return}}for(;g--;)for(f=3;f--;)for(d=9;d--;){h=0;i=[];a=3*g;for(b=3*(g+1);a<b;++a){c=3*f;for(e=3*(f+1);c<
e;++c)if(this.b[a][c]===null&&this.a[a][c][d]===true){++h;i=[a,c,d]}}if(h==1){this.c(i[0],i[1],i[2]);this.e();return}}},k:function(){for(var a=10,b=[],c=[],e,d=9,g,f;d--;){for(g=9;g--;){e=0;for(f=9;f--;)this.a[d][g][f]===true&&++e;if(e<a&&e>1){a=e;b[0]=d;b[1]=g}if(a==2)break}if(a==2)break}for(f=9;f--;)this.a[b[0]][b[1]][f]===true&&c.push(f);for(d=c.length;d--;){a=new k(this.b);a.g();a.c(b[0],b[1],c[d],false);if(a.i()){for(d=9;d--;)for(g=9;g--;)this.b[d][g]===null&&this.c(d,g,a.b[d][g]-1);return}}},
c:function(a,b,c,e){var d=9,g,f,h;if(typeof e=="undefined")e=true;for(this.b[a][b]=c+1;d--;)this.a[d][b][c]=this.a[a][d][c]=this.a[a][b][d]=false;g=a-a%3+3;h=b-b%3+3;for(d=a-a%3;d<g;++d)for(f=b-b%3;f<h;++f)this.a[d][f][c]=false;this.a[a][b][c]=true;e===true&&this.l(a,b,c+1)},j:function(){for(var a=9,b;a--;)for(b=9;b--;)if(this.b[a][b]===null)return false;return true},f:function(){for(var a=9,b,c,e;a--;)for(b=9;b--;){e=false;for(c=9;c--;)if(this.a[a][b][c]===true){e=true;break}if(!e)return true}return false}};function l(){for(var a=[],b=9,c,e;b--;){a[b]=[];for(c=9;c--;){e=parseInt(document.getElementById("input_"+b+"_"+c).value,10);a[b][c]=isNaN(e)?null:e}}return a}function m(a){for(var b=a.length,c;b--;)for(c=a[b].length;c--;)n(b,c,a[b][c])}function n(a,b,c){if(c!==null)document.getElementById("input_"+a+"_"+b).value=c}function o(a){a.className=a.value!=""&&[1,2,3,4,5,6,7,8,9].contains(parseInt(a.value,10))===false?"error":""}
function p(){for(var a=document.getElementById("input").getElementsByTagName("input"),b=a.length;b--;)o(a[b]);return getElementsByClassName(document.getElementById("input"),"error").length===0?true:false}function q(){r=(new Date).getTime();if(!p()){alert("Check input");return false}s=new k(l(),n,function(a){a===false&&alert("Got stuck, possibly impossible.");a=(new Date).getTime()-r;document.getElementById("timer").innerHTML="Solved in "+a+"ms"});s.i()}var s,r;
(function(){if(typeof Array.prototype.contains=="undefined")Array.prototype.contains=function(a){for(var b=this.length;b--;)if(this[b]===a)return true;return false};if(typeof window.addEventListener=="undefined"&&typeof window.attachEvent!="undefined")window.addEventListener=function(a,b){window.attachEvent("on"+a,b)};if(typeof window.getElementsByClassName=="undefined")window.getElementsByClassName=function(a,b){if(a.getElementsByClassName)return a.getElementsByClassName(b);else{a=a.getElementsByTagName("*");
for(var c=[],e=0,d=a.length;e<d;++e)a[e].className==b&&c.push(a[e]);return c}};window.addEventListener("load",function(){try{document.getElementById("solveButton").addEventListener("click",function(){q();return true},false);document.getElementById("sudokuForm").addEventListener("blur",function(b){["button","reset"].contains(b.target.type)||o(b.target)},true)}catch(a){if(typeof window.attachEvent!="undefined"){document.getElementById("solveButton").attachEvent("onclick",function(){q();return true});
document.getElementById("sudokuForm").attachEvent("onblur",function(b){["button","reset"].contains(b.target.type)||o(b.target)})}}m([[null,9,null,2,6,null,null,1,null],[3,null,null,null,null,9,4,null,5],[null,1,null,null,null,null,null,null,null],[null,5,null,1,null,2,null,null,3],[4,null,null,null,null,null,null,null,2],[9,null,null,3,null,6,null,7,null],[null,null,null,null,null,null,null,5,null],[7,null,5,6,null,null,null,null,1],[null,8,null,null,3,5,null,9,null]])},false)})();
