function j(a,b,c){this.l=typeof b=="function"?b:function(){};this.d=typeof c=="function"?c:function(){};this.input=a;this.h=false}
j.prototype={g:function(){var a,b,c;this.b=[];this.a=[];for(a=0;a<9;++a){this.a[a]=[];this.b[a]=[];for(b=0;b<9;++b){this.a[a][b]=[];this.b[a][b]=null;for(c=0;c<9;++c)this.a[a][b][c]=true}}for(a=0;a<9;++a)for(b=0;b<9;++b){c=parseInt(this.input[a][b],10);isNaN(c)||this.c(a,b,c-1,false)}this.h=true;if(this.f()){this.d(false);return false}},i:function(){this.h||this.g();this.e();if(this.j()){this.d(true);return true}if(this.f()){this.d(false);return false}this.k();if(this.j()){this.d(true);return true}this.d(false);
return false},e:function(){var a,b,c,e,d,f,g,h,i;for(a=0;a<9;++a)for(b=0;b<9;++b){e=0;d=[];f=0;g=[];h=0;i=[];for(c=0;c<9;c++){if(this.b[a][b]===null&&this.a[a][b][c]===true){++e;d=[a,b,c]}if(this.b[a][c]===null&&this.a[a][c][b]===true){++f;g=[a,c,b]}if(this.b[c][a]===null&&this.a[c][a][b]===true){++h;i=[c,a,b]}}e==1&&this.c(d[0],d[1],d[2]);f==1&&this.c(g[0],g[1],g[2]);h==1&&this.c(i[0],i[1],i[2]);if(e==1||f==1||h==1){this.e();return}}for(e=0;e<3;++e)for(d=0;d<3;++d)for(c=0;c<9;++c){f=0;g=[];for(a=
3*e;a<3*(e+1);++a)for(b=3*d;b<3*(d+1);++b)if(this.b[a][b]===null&&this.a[a][b][c]===true){++f;g=[a,b,c]}if(f==1){this.c(g[0],g[1],g[2]);this.e();return}}},k:function(){var a=10,b=[],c=[],e,d,f,g;for(d=0;d<9;++d){for(f=0;f<9;++f){for(g=e=0;g<9;++g)this.a[d][f][g]===true&&++e;if(e<a&&e>1){a=e;b[0]=d;b[1]=f}if(a==2)break}if(a==2)break}for(g=0;g<9;++g)this.a[b[0]][b[1]][g]===true&&c.push(g);d=0;for(xLim=c.length;d<xLim;++d){a=new j(this.b);a.g();a.c(b[0],b[1],c[d],false);if(a.i()){for(d=0;d<9;++d)for(f=
0;f<9;++f)this.b[d][f]===null&&this.c(d,f,a.b[d][f]-1);return}}},c:function(a,b,c,e){var d,f,g,h;if(typeof e=="undefined")e=true;this.b[a][b]=c+1;for(d=0;d<9;++d){this.a[d][b][c]=false;this.a[a][d][c]=false;this.a[a][b][d]=false}g=a-a%3+3;h=b-b%3+3;for(d=a-a%3;d<g;++d)for(f=b-b%3;f<h;++f)this.a[d][f][c]=false;this.a[a][b][c]=true;e===true&&this.l(a,b,c+1)},j:function(){var a,b;for(a=0;a<9;++a)for(b=0;b<9;++b)if(this.b[a][b]===null)return false;return true},f:function(){var a,b,c,e;for(a=0;a<9;++a)for(b=
0;b<9;++b){e=false;for(c=0;c<9;++c)if(this.a[a][b][c]===true){e=true;break}if(!e)return true}return false}};function k(){var a=[],b,c,e;for(b=0;b<9;++b){a[b]=[];for(c=0;c<9;++c){e=parseInt(document.getElementById("input_"+b+"_"+c).value,10);a[b][c]=isNaN(e)?null:e}}return a}function l(a){var b,c,e,d;b=0;for(e=a.length;b<e;++b){c=0;for(d=a[b].length;c<d;++c)m(b,c,a[b][c])}}function m(a,b,c){a=document.getElementById("input_"+a+"_"+b);if(c!==null)a.value=c}
function n(a){a.className=a.value!=""&&[1,2,3,4,5,6,7,8,9].contains(parseInt(a.value,10))===false?"error":""}function o(){var a=document.getElementById("input").getElementsByTagName("input"),b,c;b=0;for(c=a.length;b<c;++b)n(a[b]);return getElementsByClassName(document.getElementById("input"),"error").length===0?true:false}function p(){if(!o()){alert("Check input");return false}q=new j(k(),m,function(a){a===false&&alert("Got stuck, possibly impossible.")});q.i()}var q;
(function(){if(typeof Array.prototype.contains=="undefined")Array.prototype.contains=function(a){for(var b=0,c=this.length;b<c;b++)if(this[b]===a)return true;return false};if(typeof window.addEventListener=="undefined"&&typeof window.attachEvent!="undefined")window.addEventListener=function(a,b){window.attachEvent("on"+a,b)};if(typeof window.getElementsByClassName=="undefined")window.getElementsByClassName=function(a,b){if(a.getElementsByClassName)return a.getElementsByClassName(b);else{a=a.getElementsByTagName("*");
for(var c=[],e=0,d=a.length;e<d;++e)a[e].className==b&&c.push(a[e]);return c}};window.addEventListener("load",function(){try{document.getElementById("solveButton").addEventListener("click",function(){p();return true},false);document.getElementById("sudokuForm").addEventListener("blur",function(b){["button","reset"].contains(b.target.type)||n(b.target)},true)}catch(a){if(typeof window.attachEvent!="undefined"){document.getElementById("solveButton").attachEvent("onclick",function(){p();return true});
document.getElementById("sudokuForm").attachEvent("onblur",function(b){["button","reset"].contains(b.target.type)||n(b.target)})}}l([[null,9,null,2,6,null,null,1,null],[3,null,null,null,null,9,4,null,5],[null,1,null,null,null,null,null,null,null],[null,5,null,1,null,2,null,null,3],[4,null,null,null,null,null,null,null,2],[9,null,null,3,null,6,null,7,null],[null,null,null,null,null,null,null,5,null],[7,null,5,6,null,null,null,null,1],[null,8,null,null,3,5,null,9,null]])},false)})();